prefectures = [
  { id: 1, name: "hokkaido"},
  { id: 2, name: "aomori"},
  { id: 3, name: "iwate"},
  { id: 4, name: "miyagi"},
  { id: 5, name: "akita"},
  { id: 6, name: "yamagata"},
  { id: 7, name: "fukushima"},
  { id: 8, name: "ibaraki"},
  { id: 9, name: "tochigi"},
  { id: 10, name: "gunma"},
  { id: 11, name: "saitama"},
  { id: 12, name: "chiba"},
  { id: 13, name: "tokyo"},
  { id: 14, name: "kanagawa"},
  { id: 15, name: "niigata"},
  { id: 16, name: "toyama"},
  { id: 17, name: "ishikawa"},
  { id: 18, name: "fukui"},
  { id: 19, name: "yamanashi"},
  { id: 20, name: "nagano"},
  { id: 21, name: "gifu"},
  { id: 22, name: "shizuoka"},
  { id: 23, name: "aichi"},
  { id: 24, name: "mie"},
  { id: 25, name: "shiga"},
  { id: 26, name: "kyoto"},
  { id: 27, name: "osaka"},
  { id: 28, name: "hyogo"},
  { id: 29, name: "nara"},
  { id: 30, name: "wakayama"},
  { id: 31, name: "tottori"},
  { id: 32, name: "shimane"},
  { id: 33, name: "okayama"},
  { id: 34, name: "hiroshima"},
  { id: 35, name: "yamaguchi"},
  { id: 36, name: "tokushima"},
  { id: 37, name: "kagawa"},
  { id: 38, name: "ehime"},
  { id: 39, name: "kochi"},
  { id: 40, name: "fukuoka"},
  { id: 41, name: "saga"},
  { id: 42, name: "nagasaki"},
  { id: 43, name: "kumamoto"},
  { id: 44, name: "oita"},
  { id: 45, name: "miyazaki"},
  { id: 46, name: "kagoshima"},
  { id: 47, name: "okinawa"}
]
  
prefectures.each do |prefecture|
  Prefecture.find_or_create_by!(prefecture)
end

puts "都道府県を登録しました！"
