# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end

  # Create prefectures if none exist
  if Prefecture.none?
    prefectures = [
      { id: 1, name: "hokkaido"},
      { id: 2, name: "aomori"},
      { id: 3, name: "iwate"},
      { id: 4, name: "miyagi"},
      { id: 5, name: "akita"},
      { id: 6, name: "yamagata"},
      { id: 7, name: "fukushima"},
      { id: 8, name: "ibaraki"},
      { id: 9, name: "tochigi"},
      { id: 10, name: "gunma"},
      { id: 11, name: "saitama"},
      { id: 12, name: "chiba"},
      { id: 13, name: "tokyo"},
      { id: 14, name: "kanagawa"},
      { id: 15, name: "niigata"},
      { id: 16, name: "toyama"},
      { id: 17, name: "ishikawa"},
      { id: 18, name: "fukui"},
      { id: 19, name: "yamanashi"},
      { id: 20, name: "nagano"},
      { id: 21, name: "gifu"},
      { id: 22, name: "shizuoka"},
      { id: 23, name: "aichi"},
      { id: 24, name: "mie"},
      { id: 25, name: "shiga"},
      { id: 26, name: "kyoto"},
      { id: 27, name: "osaka"},
      { id: 28, name: "hyogo"},
      { id: 29, name: "nara"},
      { id: 30, name: "wakayama"},
      { id: 31, name: "tottori"},
      { id: 32, name: "shimane"},
      { id: 33, name: "okayama"},
      { id: 34, name: "hiroshima"},
      { id: 35, name: "yamaguchi"},
      { id: 36, name: "tokushima"},
      { id: 37, name: "kagawa"},
      { id: 38, name: "ehime"},
      { id: 39, name: "kochi"},
      { id: 40, name: "fukuoka"},
      { id: 41, name: "saga"},
      { id: 42, name: "nagasaki"},
      { id: 43, name: "kumamoto"},
      { id: 44, name: "oita"},
      { id: 45, name: "miyazaki"},
      { id: 46, name: "kagoshima"},
      { id: 47, name: "okinawa"}
    ]
    
    prefectures.each do |prefecture|
      Prefecture.create!(prefecture)
    end
  end

  # Create districts if none exist
  districts = [
    {prefecture_id: 1, name: "do-oh"},
    {prefecture_id: 1, name: "do-nan"},
    {prefecture_id: 1, name: "do-hoku"},
    {prefecture_id: 1, name: "do-toh"},
    {prefecture_id: 2, name: "aomori"},
    {prefecture_id: 2, name: "hirosaki"},
    {prefecture_id: 2, name: "hachinohe"},
    {prefecture_id: 2, name: "kuroishi"},
    {prefecture_id: 2, name: "goshogawara"},
    {prefecture_id: 2, name: "towada"},
    {prefecture_id: 2, name: "misawa"},
    {prefecture_id: 2, name: "mutsu"},
    {prefecture_id: 2, name: "tsugaru"},
    {prefecture_id: 2, name: "hirakawa"},
    {prefecture_id: 2, name: "higashi_tsugaru"},
    {prefecture_id: 2, name: "nishi_tsugaru"},
    {prefecture_id: 2, name: "naka_tsugaru"},
    {prefecture_id: 2, name: "minami_tsugaru"},
    {prefecture_id: 2, name: "kita_tsugaru"},
    {prefecture_id: 2, name: "kamikita"},
    {prefecture_id: 2, name: "shimo_kita"},
    {prefecture_id: 2, name: "san_nohe"},
    {prefecture_id: 3, name: "iwate"},
    {prefecture_id: 3, name: "morioka"},
    {prefecture_id: 3, name: "miyako"},
    {prefecture_id: 3, name: "ofunato"},
    {prefecture_id: 3, name: "hanamaki"},
    {prefecture_id: 3, name: "kitakami"},
    {prefecture_id: 3, name: "kuji"},
    {prefecture_id: 3, name: "tono"},
    {prefecture_id: 3, name: "ichinoseki"},
    {prefecture_id: 3, name: "rikuzentakata"},
    {prefecture_id: 3, name: "kamashi"},
    {prefecture_id: 3, name: "ninohe"},
    {prefecture_id: 3, name: "hachimantai"},
    {prefecture_id: 3, name: "okuzashiki"},
    {prefecture_id: 3, name: "shizukuishi"},
    {prefecture_id: 3, name: "kuzumaki"},
    {prefecture_id: 3, name: "iwate_town"},
    {prefecture_id: 3, name: "takizawa"},

    {prefecture_id: 4, name: "sendai"},
    {prefecture_id: 4, name: "ishinomaki"},
    {prefecture_id: 4, name: "shiogama"},
    {prefecture_id: 4, name: "kesennuma"},
    {prefecture_id: 4, name: "tomiya"},
    {prefecture_id: 4, name: "natori"},
    {prefecture_id: 4, name: "kakuda"},
    {prefecture_id: 4, name: "tagajo"},
    {prefecture_id: 4, name: "iwanuma"},
    {prefecture_id: 4, name: "tome"},
    {prefecture_id: 4, name: "kurihara"},
    {prefecture_id: 4, name: "higashimatsushima"},
    {prefecture_id: 4, name: "osaki"},
    {prefecture_id: 4, name: "karita"},
    {prefecture_id: 4, name: "shibata"},
    {prefecture_id: 4, name: "igu"},
    {prefecture_id: 4, name: "watari"},
    {prefecture_id: 4, name: "miyagi_gun"},
    {prefecture_id: 4, name: "shiroishi"},
    {prefecture_id: 4, name: "kami"},
    {prefecture_id: 4, name: "todaka"},
    {prefecture_id: 4, name: "oshika"},
    {prefecture_id: 4, name: "motoyoshi"},
    {prefecture_id: 4, name: "kuroki"},

    {prefecture_id: 5, name: "akita"},
    {prefecture_id: 5, name: "noshiro"},
    {prefecture_id: 5, name: "yokote"},
    {prefecture_id: 5, name: "oda"},
    {prefecture_id: 5, name: "oga"},
    {prefecture_id: 5, name: "yuzawa"},
    {prefecture_id: 5, name: "kazuno"},
    {prefecture_id: 5, name: "yuri_honjō"},
    {prefecture_id: 5, name: "katahama"},
    {prefecture_id: 5, name: "daisen"},
    {prefecture_id: 5, name: "kitaakita"},
    {prefecture_id: 5, name: "nikaho"},
    {prefecture_id: 5, name: "senboku"},

    {prefecture_id: 6, name: "yamagata"},
    {prefecture_id: 6, name: "yonezawa"},
    {prefecture_id: 6, name: "tsuruoka"},
    {prefecture_id: 6, name: "sakata"},
    {prefecture_id: 6, name: "shinjō"},
    {prefecture_id: 6, name: "sagae"},
    {prefecture_id: 6, name: "kamiyama"},
    {prefecture_id: 6, name: "murayama"},
    {prefecture_id: 6, name: "nagai"},
    {prefecture_id: 6, name: "tendō"},
    {prefecture_id: 6, name: "higashine"},
    {prefecture_id: 6, name: "obanazawa"},
    {prefecture_id: 6, name: "nanyo"},

    {prefecture_id: 7, name: "fukushima"},
    {prefecture_id: 7, name: "aizu_wakamatsu"},
    {prefecture_id: 7, name: "koriyama"},
    {prefecture_id: 7, name: "iwaki"},
    {prefecture_id: 7, name: "shirakawa"},
    {prefecture_id: 7, name: "sugakawa"},
    {prefecture_id: 7, name: "kitakata"},
    {prefecture_id: 7, name: "souma"},
    {prefecture_id: 7, name: "nihonmatsu"},
    {prefecture_id: 7, name: "tamura"},
    {prefecture_id: 7, name: "minamisoma"},
    {prefecture_id: 7, name: "date"},
    {prefecture_id: 7, name: "motomiya"},
    {prefecture_id: 7, name: "date_gun"},
    {prefecture_id: 7, name: "adachi_gun"},
    {prefecture_id: 7, name: "iwase_gun"},
    {prefecture_id: 7, name: "minamiaizu_gun"},
    {prefecture_id: 7, name: "yama_gun"},
    {prefecture_id: 7, name: "kawakuma_gun"},
    {prefecture_id: 7, name: "onuma_gun"},
    {prefecture_id: 7, name: "nishi_shirakawa_gun"},
    {prefecture_id: 7, name: "higashi_shirakawa_gun"},
    {prefecture_id: 7, name: "ishikawa_gun"},
    {prefecture_id: 7, name: "tamura_gun"},
    {prefecture_id: 7, name: "futaba_gun"},
    {prefecture_id: 7, name: "souma_gun"},

    {prefecture_id: 8, name: "ibaraki"},
    {prefecture_id: 8, name: "mito"},
    {prefecture_id: 8, name: "hitachi"},
    {prefecture_id: 8, name: "tsuchiura"},
    {prefecture_id: 8, name: "kogane"},
    {prefecture_id: 8, name: "ishioka"},
    {prefecture_id: 8, name: "yuyuki"},
    {prefecture_id: 8, name: "ryugasaki"},
    {prefecture_id: 8, name: "shimotsuma"},
    {prefecture_id: 8, name: "joso"},
    {prefecture_id: 8, name: "hitachi_ota"},
    {prefecture_id: 8, name: "takahagi"},
    {prefecture_id: 8, name: "kitaibaraki"},
    {prefecture_id: 8, name: "kasama"},
    {prefecture_id: 8, name: "toride"},
    {prefecture_id: 8, name: "ushiku"},
    {prefecture_id: 8, name: "tsukuba"},
    {prefecture_id: 8, name: "hitachinaka"},
    {prefecture_id: 8, name: "kashima"},
    {prefecture_id: 8, name: "itako"},
    {prefecture_id: 8, name: "moriya"},
    {prefecture_id: 8, name: "hitachi_omiya"},
    {prefecture_id: 8, name: "naka"},
    {prefecture_id: 8, name: "chikusei"},
    {prefecture_id: 8, name: "bandou"},
    {prefecture_id: 8, name: "inashiki"},
    {prefecture_id: 8, name: "kasumigaura"},
    {prefecture_id: 8, name: "sakuragawa"},
    {prefecture_id: 8, name: "kamisu"},
    {prefecture_id: 8, name: "namegata"},
    {prefecture_id: 8, name: "hokota"},
    {prefecture_id: 8, name: "tsukubamirai"},
    {prefecture_id: 8, name: "obitama"},
    {prefecture_id: 8, name: "naka_gun"},
    {prefecture_id: 8, name: "sarushima_gun"},
    {prefecture_id: 8, name: "yuki_gun"},
    {prefecture_id: 8, name: "kuji_gun"},
    {prefecture_id: 8, name: "kita_souma_gun"},
    {prefecture_id: 8, name: "inashiki_gun"},

    {prefecture_id: 9, name: "uzumaki"},
    {prefecture_id: 9, name: "ashikaga"},
    {prefecture_id: 9, name: "tochigi"},
    {prefecture_id: 9, name: "sano"},
    {prefecture_id: 9, name: "kanuma"},
    {prefecture_id: 9, name: "nikko"},
    {prefecture_id: 9, name: "oyama"},
    {prefecture_id: 9, name: "mooka"},
    {prefecture_id: 9, name: "otawara"},
    {prefecture_id: 9, name: "yabita"},
    {prefecture_id: 9, name: "nasushiobara"},
    {prefecture_id: 9, name: "sakura"},
    {prefecture_id: 9, name: "nasukarasuyama"},
    {prefecture_id: 9, name: "shimotsuke"},
    {prefecture_id: 9, name: "haga_gun"},

    {prefecture_id: 10, name: "maebashi"},
    {prefecture_id: 10, name: "takasaki"},
    {prefecture_id: 10, name: "kiryu"},
    {prefecture_id: 10, name: "isesaki"},
    {prefecture_id: 10, name: "ota"},
    {prefecture_id: 10, name: "numata"},
    {prefecture_id: 10, name: "tatebayashi"},
    {prefecture_id: 10, name: "shibukawa"},
    {prefecture_id: 10, name: "fujioka"},
    {prefecture_id: 10, name: "tomioka"},
    {prefecture_id: 10, name: "annaka"},
    {prefecture_id: 10, name: "midori"},
    {prefecture_id: 10, name: "agatsuma_gun"},

    {prefecture_id: 11, name: "saitama"},
    {prefecture_id: 11, name: "kawagoe"},
    {prefecture_id: 11, name: "kumagaya"},
    {prefecture_id: 11, name: "kawaguchi"},
    {prefecture_id: 11, name: "gyoda"},
    {prefecture_id: 11, name: "chichibu"},
    {prefecture_id: 11, name: "tokorozawa"},
    {prefecture_id: 11, name: "hanno"},
    {prefecture_id: 11, name: "kazo"},
    {prefecture_id: 11, name: "honjo"},
    {prefecture_id: 11, name: "higashimatsuyama"},
    {prefecture_id: 11, name: "kasukabe"},
    {prefecture_id: 11, name: "sayama"},
    {prefecture_id: 11, name: "habu"},
    {prefecture_id: 11, name: "konosu"},
    {prefecture_id: 11, name: "fukaya"},
    {prefecture_id: 11, name: "ageo"},
    {prefecture_id: 11, name: "souka"},
    {prefecture_id: 11, name: "koshigaya"},
    {prefecture_id: 11, name: "warabi"},
    {prefecture_id: 11, name: "toda"},
    {prefecture_id: 11, name: "iruma"},
    {prefecture_id: 11, name: "hatogaya"},
    {prefecture_id: 11, name: "asaka"},
    {prefecture_id: 11, name: "shiki"},
    {prefecture_id: 11, name: "wakou"},
    {prefecture_id: 11, name: "niza"},
    {prefecture_id: 11, name: "okegawa"},
    {prefecture_id: 11, name: "kuki"},
    {prefecture_id: 11, name: "shiraoka"},
    {prefecture_id: 11, name: "yachiyo"},
    {prefecture_id: 11, name: "kitamoto"},
    {prefecture_id: 11, name: "fujimino"},
    {prefecture_id: 11, name: "migoto"},
    {prefecture_id: 11, name: "fujimi"},
    {prefecture_id: 11, name: "sakado"},
    {prefecture_id: 11, name: "satte"},
    {prefecture_id: 11, name: "tsurugashima"},
    {prefecture_id: 11, name: "hidaka"},
    {prefecture_id: 11, name: "hasuda"},
    {prefecture_id: 11, name: "kitaadachi_gun"},
    {prefecture_id: 11, name: "iruma_gun"},
    {prefecture_id: 11, name: "hiki_gun"},
    {prefecture_id: 11, name: "chichibu_gun"},
    {prefecture_id: 11, name: "yoshikawa"},
    {prefecture_id: 11, name: "osato_gun"},
    {prefecture_id: 11, name: "kitasaikata_gun"},
    {prefecture_id: 11, name: "minami_saitama_gun"},
    {prefecture_id: 11, name: "kitakatsushika_gun"},
    {prefecture_id: 11, name: "kodama_gun"},

    {prefecture_id: 12, name: "chiba"},
    {prefecture_id: 12, name: "choshi"},
    {prefecture_id: 12, name: "ichikawa"},
    {prefecture_id: 12, name: "funabashi"},
    {prefecture_id: 12, name: "tateyama"},
    {prefecture_id: 12, name: "kisarazu"},
    {prefecture_id: 12, name: "matsudo"},
    {prefecture_id: 12, name: "noda"},
    {prefecture_id: 12, name: "mobara"},
    {prefecture_id: 12, name: "narita"},
    {prefecture_id: 12, name: "sakura"},
    {prefecture_id: 12, name: "togane"},
    {prefecture_id: 12, name: "asahi"},
    {prefecture_id: 12, name: "narashino"},
    {prefecture_id: 12, name: "kashiwa"},
    {prefecture_id: 12, name: "katsura"},
    {prefecture_id: 12, name: "ichihara"},
    {prefecture_id: 12, name: "nagareyama"},
    {prefecture_id: 12, name: "yachiyo"},
    {prefecture_id: 12, name: "abiko"},
    {prefecture_id: 12, name: "kamogawa"},
    {prefecture_id: 12, name: "kamagaya"},
    {prefecture_id: 12, name: "kimitsu"},
    {prefecture_id: 12, name: "futtsu"},
    {prefecture_id: 12, name: "urayasu"},
    {prefecture_id: 12, name: "yotsukaido"},
    {prefecture_id: 12, name: "soedaura"},
    {prefecture_id: 12, name: "yaguchi"},
    {prefecture_id: 12, name: "inzai"},
    {prefecture_id: 12, name: "shirai"},
    {prefecture_id: 12, name: "tomisato"},
    {prefecture_id: 12, name: "minamiboso"},
    {prefecture_id: 12, name: "sosha"},
    {prefecture_id: 12, name: "karatori"},
    {prefecture_id: 12, name: "sanbu"},
    {prefecture_id: 12, name: "isumi"},
    {prefecture_id: 12, name: "oamishirasato"},
    {prefecture_id: 12, name: "inba_gun"},
    {prefecture_id: 12, name: "karatori_gun"},
    {prefecture_id: 12, name: "sanbu_gun"},
    {prefecture_id: 12, name: "chousei_gun"},
    {prefecture_id: 12, name: "isumi_gun"},
    {prefecture_id: 12, name: "abogun"},

    {prefecture_id: 13, name: "chiyoda"},
    {prefecture_id: 13, name: "chuo"},
    {prefecture_id: 13, name: "minato"},
    {prefecture_id: 13, name: "shinjuku"},
    {prefecture_id: 13, name: "bunkyo"},
    {prefecture_id: 13, name: "taito"},
    {prefecture_id: 13, name: "sumida"},
    {prefecture_id: 13, name: "koto"},
    {prefecture_id: 13, name: "shinagawa"},
    {prefecture_id: 13, name: "meguro"},
    {prefecture_id: 13, name: "ota"},
    {prefecture_id: 13, name: "setagaya"},
    {prefecture_id: 13, name: "shibuya"},
    {prefecture_id: 13, name: "nakano"},
    {prefecture_id: 13, name: "suginami"},
    {prefecture_id: 13, name: "toshima"},
    {prefecture_id: 13, name: "kita"},
    {prefecture_id: 13, name: "arakawa"},
    {prefecture_id: 13, name: "itabashi"},
    {prefecture_id: 13, name: "nerima"},
    {prefecture_id: 13, name: "adachi"},
    {prefecture_id: 13, name: "katsushika"},
    {prefecture_id: 13, name: "edogawa"},
    {prefecture_id: 13, name: "hachioji"},
    {prefecture_id: 13, name: "tachikawa"},
    {prefecture_id: 13, name: "musashino"},
    {prefecture_id: 13, name: "mitaka"},
    {prefecture_id: 13, name: "ome"},
    {prefecture_id: 13, name: "fuchu"},
    {prefecture_id: 13, name: "akishima"},
    {prefecture_id: 13, name: "chofu"},
    {prefecture_id: 13, name: "machida"},
    {prefecture_id: 13, name: "koganei"},
    {prefecture_id: 13, name: "kodaira"},
    {prefecture_id: 13, name: "hino"},
    {prefecture_id: 13, name: "higashimurayama"},
    {prefecture_id: 13, name: "kokubunji"},
    {prefecture_id: 13, name: "kokuritsu"},
    {prefecture_id: 13, name: "gussa"},
    {prefecture_id: 13, name: "koga"},
    {prefecture_id: 13, name: "higashiyamato"},
    {prefecture_id: 13, name: "kiyose"},
    {prefecture_id: 13, name: "higashikurume"},
    {prefecture_id: 13, name: "musashimurayama"},
    {prefecture_id: 13, name: "tama"},
    {prefecture_id: 13, name: "inagi"},
    {prefecture_id: 13, name: "hamura"},
    {prefecture_id: 13, name: "akiruno"},
    {prefecture_id: 13, name: "nishi_tokyo"},
    {prefecture_id: 13, name: "nishitama"},
    {prefecture_id: 13, name: "oshima"},
    {prefecture_id: 13, name: "izuogasawara"},

    {prefecture_id: 14, name: "yokohama"},
    {prefecture_id: 14, name: "kawasaki"},
    {prefecture_id: 14, name: "yokosuka"},
    {prefecture_id: 14, name: "hiratsuka"},
    {prefecture_id: 14, name: "kamakura"},
    {prefecture_id: 14, name: "fujisawa"},
    {prefecture_id: 14, name: "odawara"},
    {prefecture_id: 14, name: "chigasaki"},
    {prefecture_id: 14, name: "zushi"},
    {prefecture_id: 14, name: "sagamihara_midori"},
    {prefecture_id: 14, name: "sagamihara_chuo"},
    {prefecture_id: 14, name: "sagamihara_minami"},
    {prefecture_id: 14, name: "miura"},
    {prefecture_id: 14, name: "hadano"},
    {prefecture_id: 14, name: "atsugi"},
    {prefecture_id: 14, name: "yamato"},
    {prefecture_id: 14, name: "isehara"},
    {prefecture_id: 14, name: "ebina"},
    {prefecture_id: 14, name: "zama"},
    {prefecture_id: 14, name: "minamiashigara"},
    {prefecture_id: 14, name: "ayase"},
    {prefecture_id: 14, name: "miura_gun"},
    {prefecture_id: 14, name: "kozogun"},
    {prefecture_id: 14, name: "nakagun"},
    {prefecture_id: 14, name: "ashigarakami_gun"},
    {prefecture_id: 14, name: "ashigarakamigun"},
    {prefecture_id: 14, name: "aikogun"},

    {prefecture_id: 15, name: "niigata"},
    {prefecture_id: 15, name: "sanjō"},
    {prefecture_id: 15, name: "kashiwazaki"},
    {prefecture_id: 15, name: "niibata"},
    {prefecture_id: 15, name: "ojiya"},
    {prefecture_id: 15, name: "kamo"},
    {prefecture_id: 15, name: "tōkamachi"},
    {prefecture_id: 15, name: "mitsuke"},
    {prefecture_id: 15, name: "murakami"},
    {prefecture_id: 15, name: "tsubame"},
    {prefecture_id: 15, name: "itoigawa"},
    {prefecture_id: 15, name: "myōkō"},
    {prefecture_id: 15, name: "gozen"},
    {prefecture_id: 15, name: "sado"},
    {prefecture_id: 15, name: "jōetsu"},
    {prefecture_id: 15, name: "agano"},
    {prefecture_id: 15, name: "tainai"},
    {prefecture_id: 15, name: "uonuma"},
    {prefecture_id: 15, name: "minamiuonuma"},
    {prefecture_id: 15, name: "higashikambara_gun"},
    {prefecture_id: 15, name: "kitakamihara_gun"},
    {prefecture_id: 15, name: "minamikamihara_gun"},
    {prefecture_id: 15, name: "nakauonuma_gun"},
    {prefecture_id: 15, name: "nishikambara_gun"},
    {prefecture_id: 15, name: "minamiuonuma_gun"},
    {prefecture_id: 15, name: "iwafune_gun"},
    {prefecture_id: 15, name: "mishima_gun"},
    {prefecture_id: 15, name: "kariwa_gun"},
  
    {prefecture_id: 16, name: "toyama"},
    {prefecture_id: 16, name: "takaoka"},
    {prefecture_id: 16, name: "uozu"},
    {prefecture_id: 16, name: "himi"},
    {prefecture_id: 16, name: "narukawa"},
    {prefecture_id: 16, name: "kure"},
    {prefecture_id: 16, name: "tonami"},
    {prefecture_id: 16, name: "oyabe"},
    {prefecture_id: 16, name: "imizu"},
    {prefecture_id: 16, name: "nanto"},
    {prefecture_id: 16, name: "shimoshinagawa_gun"},
    {prefecture_id: 16, name: "nakashinkawa_gun"},

    {prefecture_id: 17, name: "kanazawa"},
    {prefecture_id: 17, name: "nanao"},
    {prefecture_id: 17, name: "komatsu"},
    {prefecture_id: 17, name: "wajima"},
    {prefecture_id: 17, name: "suzu"},
    {prefecture_id: 17, name: "kaga"},
    {prefecture_id: 17, name: "hakui"},
    {prefecture_id: 17, name: "kahoku"},
    {prefecture_id: 17, name: "hakusan"},
    {prefecture_id: 17, name: "nomi"},
    {prefecture_id: 17, name: "nonoichi"},

    {prefecture_id: 18, name: "fukui"},
    {prefecture_id: 18, name: "tsuruga"},
    {prefecture_id: 18, name: "obama"},
    {prefecture_id: 18, name: "ono"},
    {prefecture_id: 18, name: "katsuya"},
    {prefecture_id: 18, name: "sabae"},
    {prefecture_id: 18, name: "awara"},
    {prefecture_id: 18, name: "echizen"},
    {prefecture_id: 18, name: "sakai"},
  
    {prefecture_id: 19, name: "kofu"},
    {prefecture_id: 19, name: "fujiyoshida"},
    {prefecture_id: 19, name: "tsuru"},
    {prefecture_id: 19, name: "yamanshi"},
    {prefecture_id: 19, name: "ootsuki"},
    {prefecture_id: 19, name: "nirasaki"},
    {prefecture_id: 19, name: "minami_alps"},
    {prefecture_id: 19, name: "hokuto"},
    {prefecture_id: 19, name: "kai"},
    {prefecture_id: 19, name: "fuefuki"},
    {prefecture_id: 19, name: "uenohara"},
    {prefecture_id: 19, name: "koushu"},
    {prefecture_id: 19, name: "chuo"},

    {prefecture_id: 20, name: "nagano"},
    {prefecture_id: 20, name: "matsumoto"},
    {prefecture_id: 20, name: "uedacity"},
    {prefecture_id: 20, name: "okaya"},
    {prefecture_id: 20, name: "iida"},
    {prefecture_id: 20, name: "suwa"},
    {prefecture_id: 20, name: "suzaka"},
    {prefecture_id: 20, name: "komoro"},
    {prefecture_id: 20, name: "ina"},
    {prefecture_id: 20, name: "komagane"},
    {prefecture_id: 20, name: "nakano"},
    {prefecture_id: 20, name: "omachi"},
    {prefecture_id: 20, name: "iiyama"},
    {prefecture_id: 20, name: "chano"},
    {prefecture_id: 20, name: "shiojiri"},
    {prefecture_id: 20, name: "saku"},
    {prefecture_id: 20, name: "chikuma"},
    {prefecture_id: 20, name: "toomi"},
    {prefecture_id: 20, name: "azumino"},

    {prefecture_id: 21, name: "gifu"},
    {prefecture_id: 21, name: "ogaki"},
    {prefecture_id: 21, name: "takayama"},
    {prefecture_id: 21, name: "tajimi"},
    {prefecture_id: 21, name: "seki"},
    {prefecture_id: 21, name: "nakatsugawa"},
    {prefecture_id: 21, name: "mino"},
    {prefecture_id: 21, name: "mizunami"},
    {prefecture_id: 21, name: "hashi"},
    {prefecture_id: 21, name: "ena"},
    {prefecture_id: 21, name: "minokamo"},
    {prefecture_id: 21, name: "toki"},
    {prefecture_id: 21, name: "kakamigahara"},
    {prefecture_id: 21, name: "kani"},
    {prefecture_id: 21, name: "yagata"},
    {prefecture_id: 21, name: "mizuho"},
    {prefecture_id: 21, name: "hida"},
    {prefecture_id: 21, name: "motsu"},
    {prefecture_id: 21, name: "gujo"},
    {prefecture_id: 21, name: "gero"},
    {prefecture_id: 21, name: "kaizu"},

    {prefecture_id: 22, name: "shizuoka"},
    {prefecture_id: 22, name: "hamamatsu"},
    {prefecture_id: 22, name: "numazu"},
    {prefecture_id: 22, name: "atami"},
    {prefecture_id: 22, name: "mishima"},
    {prefecture_id: 22, name: "fujinomiya"},
    {prefecture_id: 22, name: "ito"},
    {prefecture_id: 22, name: "shimada"},
    {prefecture_id: 22, name: "fuji"},
    {prefecture_id: 22, name: "iwata"},
    {prefecture_id: 22, name: "yaizu"},
    {prefecture_id: 22, name: "kakegawa"},
    {prefecture_id: 22, name: "fujieda"},
    {prefecture_id: 22, name: "gotemba"},
    {prefecture_id: 22, name: "fukuroi"},
    {prefecture_id: 22, name: "shimoda"},
    {prefecture_id: 22, name: "susono"},
    {prefecture_id: 22, name: "kosei"},
    {prefecture_id: 22, name: "izu"},
    {prefecture_id: 22, name: "omaezaki"},
    {prefecture_id: 22, name: "kikugawa"},
    {prefecture_id: 22, name: "izunokuni"},
    {prefecture_id: 22, name: "makinohara"},

    {prefecture_id: 23, name: "nagoya_tenpaku"},
    {prefecture_id: 23, name: "toyohashi"},
    {prefecture_id: 23, name: "okazaki"},
    {prefecture_id: 23, name: "ichinomiya"},
    {prefecture_id: 23, name: "seto"},
    {prefecture_id: 23, name: "handa"},
    {prefecture_id: 23, name: "kasugai"},
    {prefecture_id: 23, name: "toyokawa"},
    {prefecture_id: 23, name: "tsushima"},
    {prefecture_id: 23, name: "hakanan"},
    {prefecture_id: 23, name: "kariya"},
    {prefecture_id: 23, name: "toyota"},
    {prefecture_id: 23, name: "anjo"},
    {prefecture_id: 23, name: "nishio"},
    {prefecture_id: 23, name: "gamagori"},
    {prefecture_id: 23, name: "inuyama"},
    {prefecture_id: 23, name: "tokoname"},
    {prefecture_id: 23, name: "konan"},
    {prefecture_id: 23, name: "komaki"},
    {prefecture_id: 23, name: "inazawa"},
    {prefecture_id: 23, name: "shinshiro"},
    {prefecture_id: 23, name: "tokai"},
    {prefecture_id: 23, name: "obu"},
    {prefecture_id: 23, name: "chita"},
    {prefecture_id: 23, name: "chiryu"},
    {prefecture_id: 23, name: "owariasahi"},
    {prefecture_id: 23, name: "takahama"},
    {prefecture_id: 23, name: "iwakura"},
    {prefecture_id: 23, name: "toyotomi"},
    {prefecture_id: 23, name: "nisshin"},
    {prefecture_id: 23, name: "tahara"},
    {prefecture_id: 23, name: "aisei"},
    {prefecture_id: 23, name: "kiyosu"},
    {prefecture_id: 23, name: "kitanagoya"},
    {prefecture_id: 23, name: "yachiyo"},
    {prefecture_id: 23, name: "miyoshi"},
    {prefecture_id: 23, name: "ama"},
    {prefecture_id: 23, name: "nagakute"},
    {prefecture_id: 23, name: "aichi_gun"},
    {prefecture_id: 23, name: "nishikuwana_gun"},
    {prefecture_id: 23, name: "niwa_gun"},
    {prefecture_id: 23, name: "aichi_gun_kaibu"},
    {prefecture_id: 23, name: "chita_gun"},
    {prefecture_id: 23, name: "nukata_gun"},
    {prefecture_id: 23, name: "kitashitara_gun"},

    {prefecture_id: 24, name: "tsu"},
    {prefecture_id: 24, name: "yokkaichi"},
    {prefecture_id: 24, name: "ise"},
    {prefecture_id: 24, name: "matsusaka"},
    {prefecture_id: 24, name: "kuwana"},
    {prefecture_id: 24, name: "suzuka"},
    {prefecture_id: 24, name: "nabari"},
    {prefecture_id: 24, name: "owase"},
    {prefecture_id: 24, name: "kameyama"},
    {prefecture_id: 24, name: "toba"},
    {prefecture_id: 24, name: "kumano"},
    {prefecture_id: 24, name: "inabe"},
    {prefecture_id: 24, name: "shima"},
    {prefecture_id: 24, name: "iga"},

    {prefecture_id: 25, name: "otsu"},
    {prefecture_id: 25, name: "hikone"},
    {prefecture_id: 25, name: "nagahama"},
    {prefecture_id: 25, name: "omi_hachiman"},
    {prefecture_id: 25, name: "kusatsu"},
    {prefecture_id: 25, name: "moriyama"},
    {prefecture_id: 25, name: "ritto"},
    {prefecture_id: 25, name: "kouka"},
    {prefecture_id: 25, name: "yasu"},
    {prefecture_id: 25, name: "konan"},
    {prefecture_id: 25, name: "takashima"},
    {prefecture_id: 25, name: "higashi_omi"},
    {prefecture_id: 25, name: "maibara"},

    {prefecture_id: 26, name: "kyoto"},
    {prefecture_id: 26, name: "fukuchiyama"},
    {prefecture_id: 26, name: "maizuru"},
    {prefecture_id: 26, name: "ayabe"},
    {prefecture_id: 26, name: "uji"},
    {prefecture_id: 26, name: "miyazu"},
    {prefecture_id: 26, name: "kameoka"},
    {prefecture_id: 26, name: "joyo"},
    {prefecture_id: 26, name: "mukō"},
    {prefecture_id: 26, name: "nakaokyo"},
    {prefecture_id: 26, name: "yawata"},
    {prefecture_id: 26, name: "kyotanabe"},
    {prefecture_id: 26, name: "kyotango"},
    {prefecture_id: 26, name: "nantan"},
    {prefecture_id: 26, name: "kizugawa"},
    {prefecture_id: 26, name: "otokuni"},
    {prefecture_id: 26, name: "kuze"},
    {prefecture_id: 26, name: "tsuzuki"},
    {prefecture_id: 26, name: "soraku"},
    {prefecture_id: 26, name: "funai"},
    {prefecture_id: 26, name: "yosa"},
  
    {prefecture_id: 27, name: "osaka"},
    {prefecture_id: 27, name: "sakai"},
    {prefecture_id: 27, name: "kishiwada"},
    {prefecture_id: 27, name: "toyonaka"},
    {prefecture_id: 27, name: "ikeda"},
    {prefecture_id: 27, name: "suita"},
    {prefecture_id: 27, name: "izumiotsu"},
    {prefecture_id: 27, name: "takatsuki"},
    {prefecture_id: 27, name: "kaizuka"},
    {prefecture_id: 27, name: "moriguchi"},
    {prefecture_id: 27, name: "hirakata"},
    {prefecture_id: 27, name: "ibaraki"},
    {prefecture_id: 27, name: "yawata"},
    {prefecture_id: 27, name: "izumisano"},
    {prefecture_id: 27, name: "tomitabayashi"},
    {prefecture_id: 27, name: "neyagawa"},
    {prefecture_id: 27, name: "kawachinagano"},
    {prefecture_id: 27, name: "matsubara"},
    {prefecture_id: 27, name: "daito"},
    {prefecture_id: 27, name: "izumi"},
    {prefecture_id: 27, name: "mino"},
    {prefecture_id: 27, name: "kabarakishi"},
    {prefecture_id: 27, name: "habikino"},
    {prefecture_id: 27, name: "kadoma"},
    {prefecture_id: 27, name: "settatsu"},
    {prefecture_id: 27, name: "takashi"},
    {prefecture_id: 27, name: "fujiidera"},
    {prefecture_id: 27, name: "higasiosaka"},
    {prefecture_id: 27, name: "sennan"},
    {prefecture_id: 27, name: "shijonawate"},
    {prefecture_id: 27, name: "katano"},
    {prefecture_id: 27, name: "osakasayama"},
    {prefecture_id: 27, name: "hanan"},
    {prefecture_id: 27, name: "mishima"},
    {prefecture_id: 27, name: "toyono"},
    {prefecture_id: 27, name: "senboku"},
    {prefecture_id: 27, name: "minamikawachi"},
    {prefecture_id: 27, name: "sennan"},

    {prefecture_id: 28, name: "kobe"},
    {prefecture_id: 28, name: "himeji"},
    {prefecture_id: 28, name: "amagasaki"},
    {prefecture_id: 28, name: "akashi"},
    {prefecture_id: 28, name: "nishinomiya"},
    {prefecture_id: 28, name: "sumoto"},
    {prefecture_id: 28, name: "ashiyacity"},
    {prefecture_id: 28, name: "itami"},
    {prefecture_id: 28, name: "aioi"},
    {prefecture_id: 28, name: "toyooka"},
    {prefecture_id: 28, name: "kakogawa"},
    {prefecture_id: 28, name: "ako"},
    {prefecture_id: 28, name: "nishiwaki"},
    {prefecture_id: 28, name: "takarazuka"},
    {prefecture_id: 28, name: "miki"},
    {prefecture_id: 28, name: "takasago"},
    {prefecture_id: 28, name: "kawanishi"},
    {prefecture_id: 28, name: "ono"},
    {prefecture_id: 28, name: "sanda"},
    {prefecture_id: 28, name: "kasai"},
    {prefecture_id: 28, name: "tatsuno"},
    {prefecture_id: 28, name: "tanbasasayama"},
    {prefecture_id: 28, name: "yabu"},
    {prefecture_id: 28, name: "tanba"},
    {prefecture_id: 28, name: "minamiawaji"},
    {prefecture_id: 28, name: "asaka"},
    {prefecture_id: 28, name: "awaji"},
    {prefecture_id: 28, name: "shiso"},
    {prefecture_id: 28, name: "kato"},
    {prefecture_id: 28, name: "ibogun"},
    {prefecture_id: 28, name: "kakogun"},
    {prefecture_id: 28, name: "kanzaki"},
    {prefecture_id: 28, name: "mikata"},
    {prefecture_id: 28, name: "kawabe"},
    {prefecture_id: 28, name: "taka"},
    {prefecture_id: 28, name: "sayo"},
    {prefecture_id: 28, name: "ako"},

    {prefecture_id: 29, name: "nara"},
    {prefecture_id: 29, name: "yamato_takada"},
    {prefecture_id: 29, name: "yamato_kooriyama"},
    {prefecture_id: 29, name: "tenri"},
    {prefecture_id: 29, name: "kashihara"},
    {prefecture_id: 29, name: "sakurai"},
    {prefecture_id: 29, name: "gojo"},
    {prefecture_id: 29, name: "gosho"},
    {prefecture_id: 29, name: "ikoma"},
    {prefecture_id: 29, name: "kashiba"},
    {prefecture_id: 29, name: "katsuragi"},
    {prefecture_id: 29, name: "uda"},
    {prefecture_id: 29, name: "ikoma_gun"},
    {prefecture_id: 29, name: "ishi_gun"},
    {prefecture_id: 29, name: "kita_katsuragi_gun"},

    {prefecture_id: 30, name: "wakayama"},
    {prefecture_id: 30, name: "kainan"},
    {prefecture_id: 30, name: "hashimoto"},
    {prefecture_id: 30, name: "arida"},
    {prefecture_id: 30, name: "gobou"},
    {prefecture_id: 30, name: "tanabe"},
    {prefecture_id: 30, name: "shingu"},
    {prefecture_id: 30, name: "kinokawa"},
    {prefecture_id: 30, name: "iwade"},
    {prefecture_id: 30, name: "kaiku_gun"},
    {prefecture_id: 30, name: "ito_gun"},
    {prefecture_id: 30, name: "arida_gun"},
    {prefecture_id: 30, name: "hidaka_gun"},
    {prefecture_id: 30, name: "nishimuro_gun"},
    {prefecture_id: 30, name: "higashimuro_gun"},

    {prefecture_id: 31, name: "tottori"},
    {prefecture_id: 31, name: "yonago"},
    {prefecture_id: 31, name: "kurayoshi"},
    {prefecture_id: 31, name: "sakai"},

    {prefecture_id: 32, name: "matsue"},
    {prefecture_id: 32, name: "hamada"},
    {prefecture_id: 32, name: "izumo"},
    {prefecture_id: 32, name: "masuda"},
    {prefecture_id: 32, name: "oota"},
    {prefecture_id: 32, name: "yasugi"},
    {prefecture_id: 32, name: "gotsu"},
    {prefecture_id: 32, name: "unnan"},

    {prefecture_id: 33, name: "okayama"},
    {prefecture_id: 33, name: "kurashiki"},
    {prefecture_id: 33, name: "tsuyama"},
    {prefecture_id: 33, name: "tamano"},
    {prefecture_id: 33, name: "kasaoka"},
    {prefecture_id: 33, name: "ibara"},
    {prefecture_id: 33, name: "soja"},
    {prefecture_id: 33, name: "takahashi"},
    {prefecture_id: 33, name: "niimi"},
    {prefecture_id: 33, name: "bizen"},
    {prefecture_id: 33, name: "setouchi"},
    {prefecture_id: 33, name: "akaiwa"},
    {prefecture_id: 33, name: "maniwa"},
    {prefecture_id: 33, name: "mimasaka"},
    {prefecture_id: 33, name: "asakuchi"},

    {prefecture_id: 34, name: "hiroshima"},
    {prefecture_id: 34, name: "kure"},
    {prefecture_id: 34, name: "takehara"},
    {prefecture_id: 34, name: "mihara"},
    {prefecture_id: 34, name: "onomichi"},
    {prefecture_id: 34, name: "fukuyama"},
    {prefecture_id: 34, name: "fuchu"},
    {prefecture_id: 34, name: "sanjyou"},
    {prefecture_id: 34, name: "shobara"},
    {prefecture_id: 34, name: "otake"},
    {prefecture_id: 34, name: "higashihiroshima"},
    {prefecture_id: 34, name: "hatsukaichi"},
    {prefecture_id: 34, name: "akitakata"},
    {prefecture_id: 34, name: "etajima"},
    {prefecture_id: 34, name: "aki_gun"},
    {prefecture_id: 34, name: "yamakata_gun"},
    {prefecture_id: 34, name: "toyota_gun"},
    {prefecture_id: 34, name: "sera_gun"},
    {prefecture_id: 34, name: "kanzaki_gun"},

    {prefecture_id: 35, name: "shimonoseki"},
    {prefecture_id: 35, name: "ube"},
    {prefecture_id: 35, name: "yamaguchi"},
    {prefecture_id: 35, name: "hagi"},
    {prefecture_id: 35, name: "hofu"},
    {prefecture_id: 35, name: "shimonoseki"},
    {prefecture_id: 35, name: "iwakuni"},
    {prefecture_id: 35, name: "hikari"},
    {prefecture_id: 35, name: "nagato"},
    {prefecture_id: 35, name: "yanai"},
    {prefecture_id: 35, name: "mine"},
    {prefecture_id: 35, name: "shunan"},
    {prefecture_id: 35, name: "san'yoonoda"},

    {prefecture_id: 36, name: "tokushima"},
    {prefecture_id: 36, name: "naruto"},
    {prefecture_id: 36, name: "komatsushima"},
    {prefecture_id: 36, name: "anan"},
    {prefecture_id: 36, name: "yoshinogawa"},
    {prefecture_id: 36, name: "awa"},
    {prefecture_id: 36, name: "mima"},
    {prefecture_id: 36, name: "miyoshi"},
    {prefecture_id: 36, name: "kaifu"},

    {prefecture_id: 37, name: "takamatsu"},
    {prefecture_id: 37, name: "marugame"},
    {prefecture_id: 37, name: "sakai"},
    {prefecture_id: 37, name: "zentsuji"},
    {prefecture_id: 37, name: "kanonji"},
    {prefecture_id: 37, name: "sanuki"},
    {prefecture_id: 37, name: "higashikagawa"},
    {prefecture_id: 37, name: "mitoyo"},
    {prefecture_id: 37, name: "aozuki"},

    {prefecture_id: 38, name: "matsuyama"},
    {prefecture_id: 38, name: "imabari"},
    {prefecture_id: 38, name: "uwajima"},
    {prefecture_id: 38, name: "yahatahama"},
    {prefecture_id: 38, name: "niihama"},
    {prefecture_id: 38, name: "saijo"},
    {prefecture_id: 38, name: "ozu"},
    {prefecture_id: 38, name: "iyo"},
    {prefecture_id: 38, name: "shikokuchuo"},
    {prefecture_id: 38, name: "seiyo"},
    {prefecture_id: 38, name: "toon"},

    {prefecture_id: 39, name: "kochi"},
    {prefecture_id: 39, name: "muroto"},
    {prefecture_id: 39, name: "aki"},
    {prefecture_id: 39, name: "nangoku"},
    {prefecture_id: 39, name: "tosa"},
    {prefecture_id: 39, name: "susaki"},
    {prefecture_id: 39, name: "sukumo"},
    {prefecture_id: 39, name: "tosa_kumizu"},
    {prefecture_id: 39, name: "shimanto"},
    {prefecture_id: 39, name: "konan"},
    {prefecture_id: 39, name: "kami"},

    {prefecture_id: 40, name: "fukuoka"},
    {prefecture_id: 40, name: "kitakyushu"},
    {prefecture_id: 40, name: "omuta"},
    {prefecture_id: 40, name: "kurume"},
    {prefecture_id: 40, name: "nogata"},
    {prefecture_id: 40, name: "iizuka"},
    {prefecture_id: 40, name: "tagawa"},
    {prefecture_id: 40, name: "yanagawa"},
    {prefecture_id: 40, name: "yame"},
    {prefecture_id: 40, name: "chikugo"},
    {prefecture_id: 40, name: "okawa"},
    {prefecture_id: 40, name: "yukuhashi"},
    {prefecture_id: 40, name: "buzen"},
    {prefecture_id: 40, name: "nakama"},
    {prefecture_id: 40, name: "ogori"},
    {prefecture_id: 40, name: "chikushino"},
    {prefecture_id: 40, name: "kasuga"},
    {prefecture_id: 40, name: "onojō"},
    {prefecture_id: 40, name: "munakata"},
    {prefecture_id: 40, name: "dazaifu"},
    {prefecture_id: 40, name: "koga"},
    {prefecture_id: 40, name: "fukutsu"},
    {prefecture_id: 40, name: "ukihashi"},
    {prefecture_id: 40, name: "miyawaka"},
    {prefecture_id: 40, name: "kama"},
    {prefecture_id: 40, name: "asakura"},
    {prefecture_id: 40, name: "miyama"},
    {prefecture_id: 40, name: "ito"},
    {prefecture_id: 40, name: "nakagawa"},

    {prefecture_id: 41, name: "saga"},
    {prefecture_id: 41, name: "karatsu"},
    {prefecture_id: 41, name: "tosu"},
    {prefecture_id: 41, name: "taku"},
    {prefecture_id: 41, name: "imari"},
    {prefecture_id: 41, name: "takeo"},
    {prefecture_id: 41, name: "kashima"},
    {prefecture_id: 41, name: "ogishi"},
    {prefecture_id: 41, name: "ureshino"},
    {prefecture_id: 41, name: "kanzaki"},
    {prefecture_id: 41, name: "kijima"},
    {prefecture_id: 41, name: "sanyouki"},
    {prefecture_id: 41, name: "nishimatsura"},
    {prefecture_id: 41, name: "kanzaki"},
    {prefecture_id: 41, name: "fujitsu"},
    {prefecture_id: 41, name: "higashimatsura"},

    {prefecture_id: 42, name: "nagasaki"},
    {prefecture_id: 42, name: "sasebo"},
    {prefecture_id: 42, name: "shimabara"},
    {prefecture_id: 42, name: "isahaya"},
    {prefecture_id: 42, name: "omura"},
    {prefecture_id: 42, name: "hirado"},
    {prefecture_id: 42, name: "matsura"},
    {prefecture_id: 42, name: "tsushima"},
    {prefecture_id: 42, name: "ikki"},
    {prefecture_id: 42, name: "goto"},
    {prefecture_id: 42, name: "nishikai"},
    {prefecture_id: 42, name: "unzen"},
    {prefecture_id: 42, name: "minamishimabara"},
    {prefecture_id: 42, name: "nishisonogi"},
    {prefecture_id: 42, name: "higashisonogi"},
    {prefecture_id: 42, name: "kitamatsura"},
    {prefecture_id: 42, name: "minamimatsura"},

    {prefecture_id: 43, name: "kumamoto"},
    {prefecture_id: 43, name: "yatsushiro"},
    {prefecture_id: 43, name: "hitoyoshi"},
    {prefecture_id: 43, name: "arao"},
    {prefecture_id: 43, name: "minamata"},
    {prefecture_id: 43, name: "tamana"},
    {prefecture_id: 43, name: "yamaga"},
    {prefecture_id: 43, name: "kikuchi"},
    {prefecture_id: 43, name: "uto"},
    {prefecture_id: 43, name: "kamitakuma"},
    {prefecture_id: 43, name: "uku"},
    {prefecture_id: 43, name: "aso"},
    {prefecture_id: 43, name: "amakusa"},
    {prefecture_id: 43, name: "koshi"},
    {prefecture_id: 43, name: "kamimashiki"},
    {prefecture_id: 43, name: "kikuchi"},
    {prefecture_id: 43, name: "kurume"},
    {prefecture_id: 43, name: "kuma"},
    {prefecture_id: 43, name: "tamana"},
    {prefecture_id: 43, name: "arida"},

    {prefecture_id: 44, name: "oita"},
    {prefecture_id: 44, name: "beppu"},
    {prefecture_id: 44, name: "nakatsu"},
    {prefecture_id: 44, name: "hita"},
    {prefecture_id: 44, name: "saiki"},
    {prefecture_id: 44, name: "usuki"},
    {prefecture_id: 44, name: "tsukumi"},
    {prefecture_id: 44, name: "takeda"},
    {prefecture_id: 44, name: "bungotakada"},
    {prefecture_id: 44, name: "kitsuki"},
    {prefecture_id: 44, name: "usa"},
    {prefecture_id: 44, name: "bungoono"},
    {prefecture_id: 44, name: "yufu"},
    {prefecture_id: 44, name: "kunisaki"},
    {prefecture_id: 44, name: "kusu"},
    {prefecture_id: 44, name: "hayami"},
    {prefecture_id: 44, name: "higashikuni"},

    {prefecture_id: 45, name: "miyazaki"},
    {prefecture_id: 45, name: "miyakonojō"},
    {prefecture_id: 45, name: "noheji"},
    {prefecture_id: 45, name: "nichi"},
    {prefecture_id: 45, name: "kobayashi"},
    {prefecture_id: 45, name: "hyuga"},
    {prefecture_id: 45, name: "kushima"},
    {prefecture_id: 45, name: "nishitō"},
    {prefecture_id: 45, name: "ebino"},
    {prefecture_id: 45, name: "kitamorokata"},
    {prefecture_id: 45, name: "nishimorokata"},
    {prefecture_id: 45, name: "higashimorokata"},
    {prefecture_id: 45, name: "kodama"},
    {prefecture_id: 45, name: "higashiusu"},
    {prefecture_id: 45, name: "nishiusu"},

    {prefecture_id: 46, name: "kagoshima"},
    {prefecture_id: 46, name: "kanoya"},
    {prefecture_id: 46, name: "makurazaki"},
    {prefecture_id: 46, name: "akune"},
    {prefecture_id: 46, name: "izumi"},
    {prefecture_id: 46, name: "isa"},
    {prefecture_id: 46, name: "ibusuki"},
    {prefecture_id: 46, name: "nishinoomote"},
    {prefecture_id: 46, name: "tarumizu"},
    {prefecture_id: 46, name: "satumakawauchi"},
    {prefecture_id: 46, name: "kirishima"},
    {prefecture_id: 46, name: "aira"},
    {prefecture_id: 46, name: "hioki"},
    {prefecture_id: 46, name: "ichikikushikino"},
    {prefecture_id: 46, name: "sono"},
    {prefecture_id: 46, name: "minamisatsuma"},
    {prefecture_id: 46, name: "shibushi"},
    {prefecture_id: 46, name: "amami"},
    {prefecture_id: 46, name: "minamikyuushu"},
    {prefecture_id: 46, name: "kagoshima"},
    {prefecture_id: 46, name: "satsuma"},
    {prefecture_id: 46, name: "izumi"},
    {prefecture_id: 46, name: "aira"},
    {prefecture_id: 46, name: "sono"},
    {prefecture_id: 46, name: "kibutsu"},
    {prefecture_id: 46, name: "kumage"},
    {prefecture_id: 46, name: "oshima"},

    {prefecture_id: 47, name: "naha"},
    {prefecture_id: 47, name: "ginowan"},
    {prefecture_id: 47, name: "ishigaki"},
    {prefecture_id: 47, name: "urasoe"},
    {prefecture_id: 47, name: "nago"},
    {prefecture_id: 47, name: "itoman"},
    {prefecture_id: 47, name: "okinawa"},
    {prefecture_id: 47, name: "tomigusuku"},
    {prefecture_id: 47, name: "uruma"},
    {prefecture_id: 47, name: "miyakojima"},
    {prefecture_id: 47, name: "nanjō"},
    {prefecture_id: 47, name: "nakagami"},
    {prefecture_id: 47, name: "shimajiri"},
    {prefecture_id: 47, name: "yaeyama"}
  ]
  districts.each do |district|
    District.find_or_create_by!(district)
  end

  if Area.none?
    areas = [
      {prefecture_id: 1, district_id: 1, name: "札幌・すすきの" }, 
      {prefecture_id: 1, district_id: 1, name: "札幌駅" },
      {prefecture_id: 1, district_id: 1, name: "大通・狸小路" },
      {prefecture_id: 1, district_id: 1, name: "札幌市中央区" },
      {prefecture_id: 1, district_id: 1, name: "札幌市西区" },
      {prefecture_id: 1, district_id: 1, name: "札幌市手稲区" },
      {prefecture_id: 1, district_id: 1, name: "札幌市北区" },
      {prefecture_id: 1, district_id: 1, name: "札幌市白石区" },
      {prefecture_id: 1, district_id: 1, name: "札幌市厚別区" },
      {prefecture_id: 1, district_id: 1, name: "札幌市豊平区" },
      {prefecture_id: 1, district_id: 1, name: "札幌市南区" },
      {prefecture_id: 1, district_id: 1, name: "小樽市" }
    ]
    areas.each do |area|
      Area.create!(area)
    end
  end

  if Genre.none?
    genres = [
      {name: "カフェ", rubi: "cafe", description: "静かな時間を過ごせる、心癒されるカフェ"}, #(A quiet space to relax and unwind)
      {name: "カジュアルバー", rubi: "casual-bar", description: "気軽に入りやすいバー"}, # (Craft cocktails for a special night)
      {name: "カクテルバー", rubi: "cocktail-bar", description: "華やかなカクテルで特別な夜を演出"}, # (Craft cocktails for a special night)
      {name: "ワインバー", rubi: "wine-bar", description: "選び抜かれたワインをじっくり堪能する空間"}, # (Enjoy carefully selected wines in style)
      {name: "オーセンティックバー", rubi: "authentic-bar", description: "本格派カクテルと上質な時間を楽しむ高級バー"}, # (Experience quality in a true authentic bar)
      {name: "シーシャバー", rubi: "shisha-bar", description: "異国の香り漂うシーシャでリラックス"}, # (Relax with exotic shisha flavors)
      {name: "カラオケバー", rubi: "karaoke-bar", description: "歌って飲んでストレス発散、楽しさ満点！"} , # (Sing your heart out with a drink in hand!)
      {name: "ダーツバー", rubi: "darts-bar", description: "ダーツとお酒で盛り上がる大人の遊び場"}, # (Fun and games with darts and drinks)
      {name: "プールバー", rubi: "pool-bar", description: "ビリヤードと共にお酒を楽しむ社交の場"}, # (Enjoy pool and drinks in a social setting)
      {name: "ダイニングバー", rubi: "dining-bar", description: "美味しい食事とお酒が同時に楽しめる贅沢空間"}, # (Indulge in fine food and drinks together)
      {name: "スポーツバー", rubi: "sports-bar", description: "大画面で観戦しながら仲間と盛り上がれるバー"}, # (Cheer on your team with friends in a bar)
      {name: "クラブ", rubi: "club", description: "音楽とダンスで夜を楽しむエンタメバー"}, # (Dance and party the night away)
      {name: "コンセプトカフェ", rubi: "concept-cafe", description: "個性的なテーマで非日常を楽しめるカフェ"}, # (Unique themes for a special cafe experience)
      {name: "コンセプトバー", rubi: "concept-bar", description: "独自の世界観でお酒を楽しむ特別なバー"}, # (Explore distinct vibes and drinks)
      {name: "スナック・パブ", rubi: "snack-pub", description: "気軽に立ち寄れる、アットホームな雰囲気"}, # (Casual, homey atmosphere for a quick drink)
      {name: "ガールズバー", rubi: "girls-bar", description: "楽しい会話とお酒を楽しめる女性接客のバー"}, # (Friendly female staff and drinks to enjoy)
      {name: "メンパブ", rubi: "mens-pub", description: "男性スタッフとの楽しいひとときを過ごせるパブ"} # (Enjoy a fun time with male staff)
    ]
   
    genres.each do |genre|
      Genre.create!(genre)
    end
  end

# 事前に50個のタグを登録する
tags = [
  "おしゃれ", "隠れ家", "アットホーム", "個室あり", "カラオケあり", "ダーツあり", "バー", 
  "コンカフェ", "ガールズバー", "ラウンジ", "シャンパンタワー", "お通しなし", "深夜営業", 
  "昼間営業", "クラシック", "ジャズ", "ロック", "ポップ", "ワインバー", "ウイスキー", 
  "カクテル豊富", "ビール", "日本酒", "焼酎", "リキュール", "フルーツカクテル", "ノンアルコール", 
  "手作り料理", "つまみ", "グリル", "ビストロ", "テキーラ", "ラム酒", "サプライズ対応", 
  "生演奏", "DJ", "ライブ", "スポーツ観戦", "大画面テレビ", "外国語メニュー", "英語対応", 
  "カップルシート", "女子会", "デート向き", "友達同士", "一人で気軽に", "貸し切り可", 
  "イベント開催", "ドレスコードあり", "喫煙可", "禁煙"
]

tags.each do |tag_name|
  Label.find_or_create_by(name: tag_name)
end

puts "#{tags.size}個のタグを登録しました！"
